---
- name: Example with single pool
  hosts: "{{ targets }}"
  vars:
    timesync_ntp_servers:
      - hostname: 2.pool.ntp.org
        pool: true
        iburst: true
  roles:
    - fedora.linux_system_roles.timesync
